name: smart_net_qr_scanner
description: A Flutter app for QR scanning
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.3
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  mobile_scanner: ^5.1.1
  equatable: ^2.0.5
  get_it: ^7.6.0
  flutter_svg: ^2.0.7
  logger: ^2.0.2
  http: ^1.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png

# App icon configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#FFFFFF" # Background color for adaptive icons
  adaptive_icon_foreground: "assets/app_icon.png"
  min_sdk_android: 21
